### ISSUE TITLE
Mantain scroll sync after off/on

### ISSUE THREAD

**Issue by mymage** [dqisme/vscode-sync-scroll#1]
It can be useful to sync scrolling without realign the row number.

Example:
- Open file A and file B
- Deactivate sync
- Scroll A or B to pair the code you want to compare, but having different row number.
- Activate sync

Actual:
- When you scroll the files realign to the same row number

Desired:
- When you scroll 5 line, each file scroll 5 lines indipendentily by the row position.

Maybe you can set three state: 
- OFF: don't sync
- ON: sync scroll without row number pair
- PAIR: sync scroll with row number pair

**Comment by dqisme** [comment]
> It can be useful to sync scrolling without realign the row number.
> 
> Example:
> 
> * Open file A and file B
> * Deactivate sync
> * Scroll A or B to pair the code you want to compare, but having different row number.
> * Activate sync
> 
> Actual:
> 
> * When you scroll the files realign to the same row number
> 
> Desired:
> 
> * When you scroll 5 line, each file scroll 5 lines indipendentily by the row position.
> 
> Maybe you can set three state:
> 
> * OFF: don't sync
> * ON: sync scroll without row number pair
> * PAIR: sync scroll with row number pair

Got your idea. Thanks for that!

I was thinking about it may have multiple modes for different "sync" ways. For example, it could align by the ratio between two different length pages. It could also just sync the offset between two different starting position pages, etc.

**Comment by mymage** [comment]
> Got your idea. Thanks for that!
> 
> I was thinking about it may have multiple modes for different "sync" ways. For example, it could align by the ratio between two different length pages. It could also just sync the offset between two different starting position pages, etc.

If you can manage sync modes with "extensible" methods it can be good for future improvments.
In my experience I normaly compare similar lines of code of different projects, this is the origin of having sync without rows number pair.
But other developers sure have diffrent needs.
Let the option selection with a click on the bottom bar for me is very useful.
Thanks for your work.

**Comment by JoBrad** [comment]
If I understand correctly, OP is asking for an offset to the scroll sync?

**Comment by mymage** [comment]
> If I understand correctly, OP is asking for an offset to the scroll sync?

Sorry I don't understand "OP"; if means me, "asking for an offset" is a way to say that when I am at a certain row X on file A and I want to compare with the row Y (ie X+25rows) of file B, there will be an offset of 25 rows in the scroll sync.

**Comment by dqisme** [comment]
> > Got your idea. Thanks for that!
> > I was thinking about it may have multiple modes for different "sync" ways. For example, it could align by the ratio between two different length pages. It could also just sync the offset between two different starting position pages, etc.
> 
> If you can manage sync modes with "extensible" methods it can be good for future improvments.
> In my experience I normaly compare similar lines of code of different projects, this is the origin of having sync without rows number pair.
> But other developers sure have diffrent needs.
> Let the option selection with a click on the bottom bar for me is very useful.
> Thanks for your work.

You're right. Extendability.

**Comment by spinbaby** [comment]
Great job on the extension! I was about to come here and suggest this same thing but @mymage beat me to it :) But yeah thumbs up  for this. Simple example:

You have your orginal file on the other side and a changed file on the other side. You sync scroll from the beginning of the file nicely when no changes has been made but then a change comes up in the other file for lets say 2 lines added. This is where the sync goes "off-sync" and you start to curse. Easy fix re-align by turning sync off and adjust either side OR what you were discussing add offset +2 or whatever.

My vote is on just turn sync off and re-align the windows.

**Comment by dqisme** [comment]
This feature has been released on v1.1.0. Upgrade and enjoy scrolling!

**Comment by mymage** [comment]
Tested, perfect! Thanks!
