### ISSUE TITLE
Unable to switch to Offset mode

### ISSUE THREAD

**Issue by govindap11** [dqisme/vscode-sync-scroll#2]
Hi!

Thanks for the awesome extension 😃 
I am having trouble turning the **Offset** mode on.
No matter what I do, it always stays in the **Normal** mode.
![Trmi8dntBM](https://user-images.githubusercontent.com/12946378/85257264-848fb900-b4a0-11ea-8a15-af7ae7bca807.gif)

**Comment by dqisme** [comment]
Could you please tell me the environment you have this issue e.g. OS, VSC version, etc.
I will try to reproduce and debug it.

**Comment by BenjaProg** [comment]
Hey, great expansion idea indeed!
I have the same problem.
My OS is: Windows 10 Version 2004, Build: 19041.329 x64
VSC Version: 1.46.1 (portable mode) x64
Installed Expansions: Matlab, Notepad++ keymap, powershell and sync scroll of course ;-)
I tried it with the same file in different views and with a different file in each view and tried activating Offset mode in every combination order with sync scroll on/off.

**Comment by govindap11** [comment]
> Glad to hear it's helpful.
> Could you please tell me the environment you have this issue e.g. OS, VSC version, etc.
> I will try to reproduce and debug it.

Thanks for the reply!

**OS:** 
Windows 10 Enterprise 1809, Build: 17763.1282 x64

**VSC:** (Copied from the "About" window)
Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by dqisme** [comment]
Looks like some issues on Windows. I will try when I am available (seems to be next week). Sorry for the late.
________________________________

**Comment by dqisme** [comment]
Hi @govindap11 @BenjaProg thanks for your feedback!

I just published the upgrade today. Could you please try it again to see if there is still the mode changing issue(or any others) on Windows?

**Comment by dqisme** [comment]
> Hi @govindap11 @BenjaProg thanks for your feedback!
> 
> I just published the upgrade today. Could you please try it again to see if there is still the mode changing issue(or any others) on Windows?

Could you please check it when you are available please?

**Comment by govindap11** [comment]
@dqisme I'm sorry for the delay.

I just confirmed this issue, and it is working without a hitch.
Thank you so much 😄
