### ISSUE TITLE
Global user settings for initial status of extension

### ISSUE THREAD

**Issue by TobiasWantzen** [dqisme/vscode-sync-scroll#25]
It would be nice, if there would be global User settings (Preferences > Settings), which define the initial status of the extension for every new window or file view. All three states should be possible: NORMAL, OFFSET, OFF.

Up to now it is permanently set to NORMAL for splitted views.

**Comment by akinuri** [comment]
I second that. It starts scroll syncing automatically when viewing unrelated files. I have to turn it off when that happens. The times I need to sync scroll is less than the times I don't need to sync scroll. So the default (at least for me) can be `off`.

**Comment by kaedys** [comment]
Adding a +1 here, the default "on" state is nearly always disruptive for me, and I find myself disabling the extension's default-on _far_ more than actually using the extension.  The synced scroll is incredibly handy for specific comparison use-cases, but those use-cases aren't particularly common, so the default-on state is nearly _always_ incorrect for a newly-opened window/view.

**Comment by TobiasWantzen** [comment]
Since the last commit for this repo is dated back to April 2020, I’d like to show how I changed the extension to default-off.
* After installation of the extension go to VSCode’s extension folder (on my Mac it resides here: `~/.vscode/extensions/`) and edit this file `~/.vscode/extensions/dqisme.sync-scroll-1.3.0/out/states.js`
(An overview where you can find the VSCode extensions on Mac, Windows, and Linux can be found here: https://code.visualstudio.com/docs/editor/extension-marketplace#_common-questions)
* Go to this line:
https://github.com/dqisme/vscode-sync-scroll/blob/8568216d44385424e07913295c86f43a276a2613/src/states.ts#L50
* Change `protected defaultValue = ON_OFF.ON` to `protected defaultValue = ON_OFF.OFF`, save, and restart VSCode, if it’s running.

This sets the extension to default-off. I hope, this helps ...

**Comment by kaedys** [comment]
Exactly what I was looking for, @TobiasWantzen, much appreciated!

**Comment by dqisme** [comment]
Just a minute ago, I just published a new release (v1.3.1) that now you can use the only one status bar item to change the  mode with three options: NORMAL, OFFSET and OFF.
And the default mode is OFF, so I hope it won't bother you when you open a new split panels workspace 😃 

Please check it out, and thanks for your feedback 👍 @TobiasWantzen @kaedys @akinuri @QuentiumYT

**Comment by dqisme** [comment]
@QuentiumYT Especially thanks for your feedback that retrigger me into this extension, I will look into your re-version and maybe try to merge some ideas into this one, and I would be more than welcomed inviting you to collaborate on it together if you wish. 😃

**Comment by QuentiumYT** [comment]
Thanks @dqisme for coming back to this extension! It was late yesterday and couldn't create a PR directly. Sadly it breaks my fork with the new global mode, but it looks interesting!
Thanks for your proposition, I'm not an expert with typescript but I can always do some PR if I see something useful to add :)
