### ISSUE TITLE
How to turn it off

### ISSUE THREAD

**Issue by lilikapa** [dqisme/vscode-sync-scroll#26]
Hi everybody,

thanks for this wonderful tool. Sry if this is a naive question, but is it actually possible to switch "Synch Scroll" off, in case I want to work on completely independent scripts on different panes?

Many thanks in advance :)

**Comment by dqisme** [comment]
Hi @lilikapa, no worries at all :). You can switch "Sync Scroll" off by executing the command "Toggle Sync Scroll" in vscode. You should see the status bar with "Sync Scroll: OFF" after it switched off successfully. Feel free to raise if you have any further questions.

**Comment by lilikapa** [comment]
Lovely, thanks a lot!
