### ISSUE TITLE
Default to off, or persistent state after close and re-open of VSCode

### ISSUE THREAD

**Issue by solidxsnake** [dqisme/vscode-sync-scroll#3]
As in title, would be nice to have Sync Scroll disabled by default, or to remember the previous setting after closing and re-opening VSCode.

**Comment by dqisme** [comment]
Thanks for your feedback and suggestion!
I will try to persist the on/off status in vscode soon.

**Comment by dqisme** [comment]
Hi @solidxsnake 

I have upgraded the extension to 1.1.1 with the state persistence feature.
Can you check it out to see if it works for you, please?

**Comment by Shamtam** [comment]
Late reply, but works great. Thanks so much!
