### ISSUE TITLE
The verbose status bar

### ISSUE THREAD

**Issue by contributorpw** [dqisme/vscode-sync-scroll#9]
I think that the status bar of the extension is redurant.

![1606202625530](https://user-images.githubusercontent.com/5027939/100061573-4d527900-2e3f-11eb-926b-0c09a88bcdff.png)

As you can see it is placed over a sufficiently long space.

My suggestion is to reduce the status bar to a few characters. For example

1. Sync Scroll NORMAL
2. Sync Scroll OFFSET
3. Sync Scroll OFF

Also if this can be view I think if the Sync Scroll NORMAL/OFFSET is activated then Sync Scroll should be enabled programmatically.

Please review the issue and let me know what you think and hat you prefered in a PR (if there is a need for it).

**Comment by dqisme** [comment]
> I think that the status bar of the extension is redurant.
> 
> ![1606202625530](https://user-images.githubusercontent.com/5027939/100061573-4d527900-2e3f-11eb-926b-0c09a88bcdff.png)
> 
> As you can see it is placed over a sufficiently long space.
> 
> My suggestion is to reduce the status bar to a few characters. For example
> 
> 1. Sync Scroll NORMAL
> 2. Sync Scroll OFFSET
> 3. Sync Scroll OFF
> 
> Also if this can be view I think if the Sync Scroll NORMAL/OFFSET is activated then Sync Scroll should be enabled programmatically.
> 
> Please review the issue and let me know what you think and hat you prefered in a PR (if there is a need for it).

That's really a concise idea, I like it. Actually I was tangling about the long status bar and two switches for a while.
Thanks for your advice. I would try to implement it. will update you if there's any improvement.

**Comment by moxwel** [comment]
Also... Could have a setting to hide the status bar commands too?

**Comment by dqisme** [comment]
> Also... Could have a setting to hide the status bar commands too?

Hey @moxwel, thanks for the advice. For clarifying your requirement, does it mean that you want to have a setting to hide the items in the status bar but leaving the commands so that the mode can be switched in the "Show All Commands" menu or shortcuts?

**Comment by moxwel** [comment]
> > Also... Could have a setting to hide the status bar commands too?
> 
> Hey @moxwel, thanks for the advice. For clarifying your requirement, does it mean that you want to have a setting to hide the items in the status bar but leaving the commands so that the mode can be switched in the "Show All Commands" menu or shortcuts?

Exactly! Only hide the items in the status bar.

**Comment by lonix1** [comment]
Hiding the status bar items would be nice. But an even better option would be:

````json
{
  "synchronizedScrolling.statusbarItems": "show",  // or "hide" or "showWhenEnabled"
}
````

The `showWhenEnabled` options would show the statusbar item, ONLY when sync scrolling is enabled. That is the most sensible option in most cases. You don't use this extension all the time, so most of the time the statusbar would be "clean", and would notify you that sync scrolling is enabled only when you're using it.

And of course you could hide the items with `hide`.

**Comment by dqisme** [comment]
> Hiding the status bar items would be nice. But an even better option would be:
> 
> ```json
> {
>   "synchronizedScrolling.statusbarItems": "show",  // or "hide" or "showWhenEnabled"
> }
> ```
> 
> The `showWhenEnabled` options would show the statusbar item, ONLY when sync scrolling is enabled. That is the most sensible option in most cases. You don't use this extension all the time, so most of the time the statusbar would be "clean", and would notify you that sync scrolling is enabled only when you're using it.
> 
> And of course you could hide the items with `hide`.

Hi @lonix1 , thanks for your advice, for now there is always a workaround that you can disable the extension in your vscode and all the related items will not display.

**Comment by contributorpw** [comment]
@dqisme ,

thanks so much!

I'm using this ext sice https://github.com/microsoft/vscode/issues/33110#issuecomment-637829526

That's cool!
